name: latex_math_evaluator
description: A Dart library for parsing and evaluating mathematical expressions in LaTeX format.
version: 0.1.2-nightly
homepage: https://github.com/xirf/latex_math_evaluator
repository: https://github.com/xirf/latex_math_evaluator

environment:
  sdk: ^3.0.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
